## Do not edit this file manually.
## It has been automatically generated from *.org sources.

## s - character string.
## v - numeric vector.
## none - character string.
.formatNameNumeric <- function(s, v, none = " <None>"){
    if(length(v) == 0)
        paste0(s, none)
    else{
        wrk <- paste0(v, collapse=" ")
        paste0(s, wrk)
    }
}

.capturePrint <- function(x){ # used by show() methods to print polynomials
    capture.output(print(x))
}
