
## Do not edit this file manually.
## It has been automatically generated from *.org sources.

## TODO: needs more care for pretty output
##       (additional arguments: digits, etc.)
.formatNameNumeric <- function(s, v){ # s - character string; v - numeric
    if(length(v) == 0)
        paste0(s, " <None>")
    else{
        wrk <- paste0(v, collapse=" ")
        paste0(s, wrk)
    }
}

.capturePrint <- function(x){ # used by show() methods to print polynomials
    capture.output(print(x))
}
